learning_rate: 0.0001
seed: 500
output_dir: runs_extension/train_vit_best_aug_1
data_dir: /data7/Users/zyj/TAPMI/EmoGen/data/EmoSet_aug_online_bank
num_train_epochs: 15
model_arch: ViT-L/14   #ViT-L/14
train_batch_size: 64  #64
warmup_epochs: 5
weight_decay: 0.001
fix_text: True
# model_resume: /data7/Users/zyj/TAPMI/EmoGen/runs/train_vit/best.pth   85.8
model_resume: /data7/Users/zyj/TAPMI/EmoGen/runs_memorybank/baseline_Clsss_trainable_KLloss*0.001_84.87_aug/VIT_query.pth
test_only: False
cal_emotion_space: False
query_len: 32   #32
query_layer: 31
pretrained_model_name_or_path: /data7/Users/zyj/TAPMI/EmoGen/model/stable-diffusion-v1-5
